# Generated by Django 4.0.8 on 2022-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='tags',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(to='mainapp.tag'),
        ),
    ]
