#<<<<<<< HEAD
# Generated by Django 4.0.8 on 2022-11-28 10:51
#=======
# Generated by Django 4.0.8 on 2022-11-28 10:49
#>>>>>>>1d04a87fde8ad1d395cef9270b1959410f922cdf

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tag_remove_todolist_tags_todolist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag'),
        ),
    ]
